#ifndef BASEVIEWMODEL_H
#define BASEVIEWMODEL_H

#ifndef QML_ANNOTATE_ACCESS_SPECIFIER
#define QML_ANNOTATE_ACCESS_SPECIFIER(x)
#endif
#define qmls public QML_ANNOTATE_ACCESS_SPECIFIER(qmls)

#endif // BASEVIEWMODEL_H
